linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - gci
    - goconst
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/jhandguy/cloud-playground/dynamo
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/jhandguy/cloud-playground/dynamo)
