replicas: 1
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 75m
    memory: 50Mi
horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 1
  targets:
    cpu:
      type: Utilization
      averageUtilization: 70
    memory:
      type: Utilization
      averageUtilization: 50
image:
  registry: ghcr.io
  repository: jhandguy/cloud-playground/gateway
  tag: 1.0.0
prometheus:
  enabled: false
  successShareThreshold: 0.99
  latency99thPercentileThreshold: 2
consul:
  enabled: false
  ingressGateway:
    port: 8080
csi:
  enabled: false
argoRollouts:
  enabled: false
services:
  stable:
    tag: 1.0.0
    weight: 50
    matcher: never
  canary:
    tag: 1.0.0
    weight: 50
    matcher: always
