replicas: 1
resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 25m
    memory: 50Mi
horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
image:
  registry: ghcr.io
  repository: jhandguy/devops-playground/s3
  tag: 1.0.0
prometheus:
  enabled: false
  successShareThreshold: 0.99
  latency99thPercentileThreshold: 2
consul:
  enabled: false
csi:
  enabled: false
