replicas: 1
resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 25m
    memory: 50Mi
image:
  registry: ghcr.io
  repository: jhandguy/devops-playground/s3
  tag: 1.0.0
prometheus:
  sli: 0.99