linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - gci
    - goconst
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/jhandguy/devops-playground/s3