apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
      annotations:
        'consul.hashicorp.com/connect-inject': "true"
        'consul.hashicorp.com/connect-service': "{{ .Release.Name }}"
        'consul.hashicorp.com/connect-service-port': "grpc"
        'consul.hashicorp.com/connect-service-upstreams': "localstack:8081"
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: AWS_DYNAMO_ENDPOINT
              value: "localhost:8081"
            - name: AWS_DYNAMO_TABLE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: aws_dynamo_table
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: aws_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: aws_secret_access_key
            - name: DYNAMO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: dynamo_token
            - name: DYNAMO_GRPC_PORT
              value: "8080"
            - name: DYNAMO_METRICS_PORT
              value: "9090"
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 8080
            - name: metrics
              protocol: TCP
              containerPort: 9090
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: {{ .Values.image.secret }}