{{- if .Values.csi.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  parameters:
    roleName: {{ .Release.Name }}
    vaultAddress: "http://{{ .Values.csi.vaultAddress }}"
    objects: |
      - objectName: "aws-region"
        secretPath: "secret/data/{{ .Release.Name }}"
        secretKey: "aws_region"
      - objectName: "aws-access-key-id"
        secretPath: "secret/data/{{ .Release.Name }}"
        secretKey: "aws_access_key_id"
      - objectName: "aws-secret-access-key"
        secretPath: "secret/data/{{ .Release.Name }}"
        secretKey: "aws_secret_access_key"
      - objectName: "aws-dynamo-table"
        secretPath: "secret/data/{{ .Release.Name }}"
        secretKey: "aws_dynamo_table"
      - objectName: "dynamo-token"
        secretPath: "secret/data/{{ .Release.Name }}"
        secretKey: "dynamo_token"

  secretObjects:
    - data:
        - objectName: aws-region
          key: aws_region
        - objectName: aws-access-key-id
          key: aws_access_key_id
        - objectName: aws-secret-access-key
          key: aws_secret_access_key
        - objectName: aws-dynamo-table
          key: aws_dynamo_table
        - objectName: dynamo-token
          key: dynamo_token
      secretName: {{ .Release.Name }}
      type: Opaque
{{- end }}
