{{- range $name, $service := .Values.services }}
---
apiVersion: autoscaling/v2beta2 # TODO: update to v2 with Kubernetes >= 1.23
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}-{{ $name }}
  {{- with $.Values.horizontalPodAutoscaler }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- range $resource, $target := .targets }}
    - type: Resource
      resource:
        name: {{ $resource }}
        target:
          type: {{ $target.type }}
          averageUtilization: {{ $target.averageUtilization }}
    {{- end }}
  {{- end }}
{{- end }}
