{{- if .Values.argoRollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      canaryService: {{ .Release.Name }}-canary
      stableService: {{ .Release.Name }}-stable
      trafficRouting:
        nginx:
          stableIngress: {{ .Release.Name }}-stable
          additionalIngressAnnotations:
            canary-by-header: X-Canary
      {{- if .Values.prometheus.enabled }}
      analysis:
        templates:
          - templateName: {{ .Release.Name }}
        startingStep: 2
      {{- end }}
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause:
            duration: 5m
        - setWeight: 75
        - pause:
            duration: 5m
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: {{ $.Release.Name }}
      containers:
        - name: {{ $.Release.Name }}
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ .Values.services.stable.tag }}"
          volumeMounts:
            {{- if $.Values.csi.enabled }}
            - name: {{ $.Release.Name }}
              mountPath: "/mnt/{{ $.Release.Name }}"
              readOnly: true
            {{- end }}
          env:
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: s3_url
            - name: DYNAMO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: dynamo_url
            - name: TEMPO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: tempo_url
            - name: S3_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: s3_token
            - name: DYNAMO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: dynamo_token
            - name: GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: gateway_token
            - name: GATEWAY_HTTP_PORT
              value: "8080"
            - name: GATEWAY_METRICS_PORT
              value: "9090"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: metrics
              protocol: TCP
              containerPort: 9090
          resources:
            {{- with $.Values.resources }}
            requests:
              memory: {{ .requests.memory }}
              cpu: {{ .requests.cpu }}
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /monitoring/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /monitoring/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 1
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /monitoring/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 1
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        {{- if $.Values.csi.enabled }}
        - name: {{ $.Release.Name }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $.Release.Name }}
        {{- end }}
{{- end }}
