{{- if .Values.consul.enabled }}
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  splits:
    {{- range $name, $service := .Values.services }}
    - service: {{ $.Release.Name }}-{{ $name }}
      weight: {{ $service.weight }}
    {{- end }}
{{- end }}
