{{- if .Values.consul.enabled }}
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  routes:
    {{- range $name, $service := .Values.services }}
    - match:
        http:
          header:
            - name: X-Canary
              exact: '{{ $service.matcher }}'
      destination:
        service: {{ $.Release.Name }}-{{ $name }}
    {{- end }}
{{- end }}
