apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  defaultSubset: '{{ .Values.deployments.prod.name }}'
  subsets:
    {{- range $name, $deployment := .Values.deployments }}
    '{{ $name }}':
      filter: '{{ $name }} in Service.Tags'
    {{- end }}