{{- range $name, $nodePort := .Values.nodePorts }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels: &labels
    app: {{ $.Release.Name }}
    {{- if not $.Values.argoRollouts.enabled }}
    name: {{ $name }}
    {{- end }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      {{- with $nodePort.http }}
      nodePort: {{ . }}
      {{- end }}
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
      {{- with $nodePort.metrics }}
      nodePort: {{ . }}
      {{- end }}
  selector: *labels
{{- end }}
