---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 30
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}
      restartPolicy: Never
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            {{- if $.Values.csi.enabled }}
            - name: {{ .Release.Name }}
              mountPath: "/mnt/{{ .Release.Name }}"
              readOnly: true
            {{- end }}
          env:
            - name: GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: gateway_token
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: gateway_url
            - name: GATEWAY_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: gateway_host
            - name: PUSHGATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: pushgateway_url
          command: ["/cli"]
          args: ["load", "test", "-r={{ .Values.test.rounds}}"]
      volumes:
        {{- if $.Values.csi.enabled }}
        - name: {{ .Release.Name }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}
        {{- end }}
