apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: gateway_api_key
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: gateway_url
            - name: PUSHGATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: pushgateway_url
          command: ["/cli"]
          args: ["load", "test", "-r={{ .Values.test.rounds}}"]
      imagePullSecrets:
        - name: {{ .Values.image.secret }}