name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install tools
        run: brew update && brew install minikube terraform

      - name: Create infratructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: chmod +x create && ./create

      - name: Run tests
        run: echo "TODO"

      - name: Destroy infrastructure
        run: chmod +x destroy && ./destroy