name: CI

on:
  push:
    branches:
      - main

env:
  go-version: 1.19
  golangci-lint-version: v1.50

jobs:
  build_go:
    name: Build (Go)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary:
          - s3
          - dynamo
          - gateway
          - cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
          check-latest: true

      - name: Install dependencies
        run: |
          brew update
          brew install protobuf protoc-gen-go protoc-gen-go-grpc

      - name: Compile proto files
        if: matrix.binary != 'cli'
        run: make compile_${{ matrix.binary }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.golangci-lint-version }}
          working-directory: ${{ matrix.binary }}

      - name: Build and run short tests
        run: make build_${{ matrix.binary }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.binary }}
          pull: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.binary }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.binary }}:1.0.0

  ci_go:
    name: CI (Go)
    needs: build_go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: consul
            rollouts-enabled: false
          - environment: nginx
            rollouts-enabled: false
          - environment: nginx
            rollouts-enabled: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
          check-latest: true

      - name: Install dependencies
        run: |
          brew update
          brew install protobuf protoc-gen-go protoc-gen-go-grpc kind terraform k6

      - name: Run all tests
        env:
          ENVIRONMENT: ${{ matrix.environment }}
          TF_VAR_argorollouts_enabled: ${{ matrix.rollouts-enabled }}
        run: make go_ci
