- name: Loki
  type: loki
  url: http://loki.loki.svc.cluster.local:3100
  access: proxy
  jsonData:
    maxLines: 1000
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: "\"(?:traceID|trace_id)\":\"(\\w+)\""
        name: TraceID
        url: "$${__value.raw}"
